import assert from "node:assert/strict";
import test from "node:test";
import type { ResolvedOrganizationContext } from "../../partner-context/domain/types";
import { IntelligenceAnalysisFactory } from "../domain/intelligenceAnalysisFactory";
import { AnalysisVersion, ConfidenceScore, CorrelationId, DiscoverySubmissionId, DiscoverySubmissionVersion, IntelligenceAnalysisId, ModelReference, ModelRunId, PromptTemplateVersion, SourceSnapshotId } from "../domain/valueObjects";
import { ArchiveIntelligenceAnalysisUseCase, GenerateIntelligenceAnalysisUseCase, GetIntelligenceAnalysisUseCase } from "./useCases";

const context = (role: "admin" | "strategist" | "viewer" = "admin"): ResolvedOrganizationContext => ({ contextKey: "ctx", actor: { user: { id: "user-1", externalSubjectId: "subject", email: "user@example.com" }, memberships: [{ id: "member", userId: "user-1", role, status: "active", scope: { organizationId: "org-1" } }] }, membership: { id: "member", userId: "user-1", role, status: "active", scope: { organizationId: "org-1" } }, organization: { id: "org-1", displayName: "Org" }, capabilities: new Set(["intelligence.request", "intelligence.read", "intelligence.review", "intelligence.archive"]), allowedVisibilities: ["internal"] });
function aggregate() { return IntelligenceAnalysisFactory.request({ id: new IntelligenceAnalysisId("analysis-1"), sourceSnapshotId: new SourceSnapshotId("snapshot-1"), discoverySubmissionId: new DiscoverySubmissionId("submission-1"), discoverySubmissionVersion: new DiscoverySubmissionVersion(1), analysisVersion: new AnalysisVersion(1), promptTemplateVersion: new PromptTemplateVersion(1), modelReference: new ModelReference("model"), policyVersion: "policy", requestedBy: "user-1", requestedAt: new Date(), correlationId: new CorrelationId("corr-1"), requestedEvent: { eventId: "request", occurredAt: new Date(), correlationId: new CorrelationId("corr-1") } }); }
function deps(analysis = aggregate(), organizationId = "org-1") { const dispatched: unknown[][] = []; return { dispatched, deps: { transactions: { run: async (fn: (c: object) => Promise<unknown>) => fn({}) }, analyses: { save: async () => {}, update: async () => {}, findById: async () => analysis, findByCorrelationId: async () => null, findBySnapshotId: async () => [], findHistoryByDiscoverySubmission: async () => [] }, snapshots: { save: async () => {}, findById: async () => ({ organizationId }), findByDiscoverySubmission: async () => [], findByOrganization: async () => [] }, reviews: { save: async () => {}, findLatest: async () => null }, events: { dispatch: async (events: unknown[]) => { dispatched.push(events); } } } as never }; }

test("generates through a transaction and dispatches events only after commit", async () => { const fixture = deps(); const result = await new GenerateIntelligenceAnalysisUseCase(fixture.deps).execute({ context: context(), analysisId: new IntelligenceAnalysisId("analysis-1"), modelRunId: new ModelRunId("run-1"), confidence: new ConfidenceScore(0.6), eventId: "generated", occurredAt: new Date() }); assert.equal(result.status, "generated"); assert.equal(fixture.dispatched.length, 1); });
test("gets DTOs and isolates another organization", async () => { const allowed = deps(); assert.equal((await new GetIntelligenceAnalysisUseCase(allowed.deps).execute({ context: context(), analysisId: new IntelligenceAnalysisId("analysis-1") })).id, "analysis-1"); await assert.rejects(() => new GetIntelligenceAnalysisUseCase(deps(aggregate(), "other").deps).execute({ context: context(), analysisId: new IntelligenceAnalysisId("analysis-1") })); });
test("denies archive without the approved capability", async () => { const fixture = deps(); await assert.rejects(() => new ArchiveIntelligenceAnalysisUseCase(fixture.deps).execute({ context: context("strategist"), analysisId: new IntelligenceAnalysisId("analysis-1"), eventId: "archive", occurredAt: new Date() })); });
test("archive rejects an invalid requested transition", async () => { const fixture = deps(); await assert.rejects(() => new ArchiveIntelligenceAnalysisUseCase(fixture.deps).execute({ context: context(), analysisId: new IntelligenceAnalysisId("analysis-1"), eventId: "archive", occurredAt: new Date() })); assert.equal(fixture.dispatched.length, 0); });
