import { requireOrganizationContextAccess } from "../../partner-context/application/requireOrganizationContextAccess";
import type { ResolvedOrganizationContext } from "../../partner-context/domain/types";
import { ConfidenceScore, CorrelationId, IntelligenceAnalysisId, ModelRunId, ReviewDecision, SourceSnapshotId } from "../domain/valueObjects";
import { IntelligenceSnapshotService, type CompletedDiscoverySource } from "../domain/services";
import type { AnalysisReviewRepository } from "../ports/AnalysisReviewRepository";
import type { DomainEventDispatcher } from "../ports/DomainEventDispatcher";
import type { IntelligenceAnalysisRepository } from "../ports/IntelligenceAnalysisRepository";
import type { IntelligenceSnapshotRepository } from "../ports/IntelligenceSnapshotRepository";
import type { TransactionRunner } from "../../lead-lifecycle/ports/TransactionRunner";

export class IntelligenceApplicationError extends Error { constructor(message: string, readonly code: "NOT_FOUND" | "FORBIDDEN" | "PERSISTENCE") { super(message); } }
type Dependencies = { transactions: TransactionRunner; analyses: IntelligenceAnalysisRepository; snapshots: IntelligenceSnapshotRepository; reviews: AnalysisReviewRepository; events: DomainEventDispatcher; };
function requireAccess(context: ResolvedOrganizationContext, capability: "intelligence.request" | "intelligence.read" | "intelligence.review" | "intelligence.archive") { try { requireOrganizationContextAccess(context, capability); } catch { throw new IntelligenceApplicationError("Access denied.", "FORBIDDEN"); } }
async function scopedAnalysis(deps: Dependencies, id: IntelligenceAnalysisId, context: ResolvedOrganizationContext) {
  const analysis = await deps.transactions.run((transaction) => deps.analyses.findById(id, transaction));
  if (!analysis) throw new IntelligenceApplicationError("Analysis not found.", "NOT_FOUND");
  const snapshot = await deps.transactions.run((transaction) => deps.snapshots.findById(analysis.sourceSnapshotId, transaction));
  if (!snapshot || snapshot.organizationId !== context.organization.id) throw new IntelligenceApplicationError("Analysis not found.", "NOT_FOUND");
  return analysis;
}
export class CreateSnapshotUseCase { constructor(private readonly deps: Dependencies) {} async execute(input: { context: ResolvedOrganizationContext; source: CompletedDiscoverySource; snapshotId: SourceSnapshotId; eventId: string; occurredAt: Date; correlationId: CorrelationId; }) { requireAccess(input.context, "intelligence.request"); if (input.source.organizationId !== input.context.organization.id) throw new IntelligenceApplicationError("Source is outside context.", "FORBIDDEN"); const created = new IntelligenceSnapshotService().create(input.source, input.snapshotId, input.occurredAt, { eventId: input.eventId, occurredAt: input.occurredAt, correlationId: input.correlationId }); await this.deps.transactions.run((tx) => this.deps.snapshots.save(created.snapshot, tx)); await this.deps.events.dispatch([created.event]); return { id: created.snapshot.id.value, submissionVersion: created.snapshot.submissionVersion.value }; } }
export class GetIntelligenceAnalysisUseCase { constructor(private readonly deps: Dependencies) {} async execute(input: { context: ResolvedOrganizationContext; analysisId: IntelligenceAnalysisId }) { requireAccess(input.context, "intelligence.read"); const analysis = await scopedAnalysis(this.deps, input.analysisId, input.context); return { id: analysis.id.value, status: analysis.status, confidence: analysis.confidence?.value }; } }
export class GenerateIntelligenceAnalysisUseCase { constructor(private readonly deps: Dependencies) {} async execute(input: { context: ResolvedOrganizationContext; analysisId: IntelligenceAnalysisId; modelRunId: ModelRunId; confidence: ConfidenceScore; eventId: string; occurredAt: Date }) { requireAccess(input.context, "intelligence.request"); const analysis = await scopedAnalysis(this.deps, input.analysisId, input.context); await this.deps.transactions.run(async (tx) => { analysis.startProcessing(input.modelRunId, { eventId: `${input.eventId}:started`, occurredAt: input.occurredAt, correlationId: analysis.correlationId }); analysis.markGenerated(input.confidence, input.occurredAt, { eventId: input.eventId, occurredAt: input.occurredAt, correlationId: analysis.correlationId }); await this.deps.analyses.update(analysis, tx); }); await this.deps.events.dispatch(analysis.pullDomainEvents()); return { id: analysis.id.value, status: analysis.status }; } }
export class ReviewIntelligenceAnalysisUseCase { constructor(private readonly deps: Dependencies) {} async execute(input: { context: ResolvedOrganizationContext; analysisId: IntelligenceAnalysisId; decision: ReviewDecision; reviewId: string; notes?: string; eventId: string; occurredAt: Date }) { requireAccess(input.context, "intelligence.review"); const analysis = await scopedAnalysis(this.deps, input.analysisId, input.context); await this.deps.transactions.run(async (tx) => { analysis.submitForReview(); analysis.recordReview(input.decision.value, { eventId: input.eventId, occurredAt: input.occurredAt, correlationId: analysis.correlationId }); await this.deps.reviews.save({ id: input.reviewId, analysisId: analysis.id.value, decision: input.decision.value, notes: input.notes, reviewedBy: input.context.actor.user.id, reviewedAt: input.occurredAt }, tx); await this.deps.analyses.update(analysis, tx); }); await this.deps.events.dispatch(analysis.pullDomainEvents()); return { id: analysis.id.value, status: analysis.status }; } }
export class ArchiveIntelligenceAnalysisUseCase { constructor(private readonly deps: Dependencies) {} async execute(input: { context: ResolvedOrganizationContext; analysisId: IntelligenceAnalysisId; eventId: string; occurredAt: Date }) { requireAccess(input.context, "intelligence.archive"); const analysis = await scopedAnalysis(this.deps, input.analysisId, input.context); await this.deps.transactions.run(async (tx) => { analysis.archive(input.occurredAt, { eventId: input.eventId, occurredAt: input.occurredAt, correlationId: analysis.correlationId }); await this.deps.analyses.update(analysis, tx); }); await this.deps.events.dispatch(analysis.pullDomainEvents()); return { id: analysis.id.value, status: analysis.status }; } }
