import { UserButton } from "@clerk/nextjs";
import Link from "next/link";
import { getOperatingIntelligenceDashboard } from "@/features/operating-intelligence/server/dashboard";
import { brainDnaTypes, brainScopes, hookBlocks, nextRadarStatuses, parseRadarStatus } from "@/features/operating-intelligence/domain/policy";
import { addBrainRecordAction, addContentHookAction, addFrictionAction, addOpportunityAction, addRadarEntryAction, askKyrumaAction, updateRadarStatusAction } from "./actions";

export const dynamic = "force-dynamic";

const field = "w-full rounded-xl border border-[var(--border)] bg-transparent px-4 py-3 text-sm";
const panel = "rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-6 md:p-8";

function WorkspaceOptions({ workspaces }: { workspaces: Awaited<ReturnType<typeof getOperatingIntelligenceDashboard>>["workspaces"] }) {
  return <>{workspaces.map((workspace) => <option key={workspace.id} value={workspace.id}>{workspace.name}</option>)}</>;
}

function ProjectOptions({ workspaces }: { workspaces: Awaited<ReturnType<typeof getOperatingIntelligenceDashboard>>["workspaces"] }) {
  return <>{workspaces.flatMap((workspace) => workspace.projects.map((project) => <option key={project.id} value={project.id}>{workspace.name} · {project.name}</option>))}</>;
}

function ScopeFields({ workspaces }: { workspaces: Awaited<ReturnType<typeof getOperatingIntelligenceDashboard>>["workspaces"] }) {
  return <div className="grid gap-3 md:grid-cols-2"><label className="text-sm">Cliente / Workspace<select className={`${field} mt-2`} name="workspaceId"><option value="">Global KYRUMA</option><WorkspaceOptions workspaces={workspaces} /></select></label><label className="text-sm">Proyecto opcional<select className={`${field} mt-2`} name="projectId"><option value="">Sin proyecto específico</option><ProjectOptions workspaces={workspaces} /></select></label></div>;
}

function readableDate(value: string) {
  return new Intl.DateTimeFormat("es-ES", { dateStyle: "medium" }).format(new Date(value));
}

export default async function OperatingIntelligencePage() {
  const dashboard = await getOperatingIntelligenceDashboard();
  const defaultDate = new Date().toISOString().slice(0, 10);

  return <main className="min-h-screen bg-[var(--background)] px-5 pb-24 pt-28 text-[var(--foreground)] md:px-8">
    <div className="mx-auto max-w-6xl">
      <header className="flex flex-wrap items-start justify-between gap-8 border-b border-[var(--border)] pb-10">
        <div><Link className="text-link text-sm" href="/access/operations"><span>←</span>Centro de operación</Link><p className="mt-8 text-xs uppercase tracking-[.28em] text-[var(--primary)]">KYRUMA AI · INTERNAL VALIDATION</p><h1 className="mt-4 text-4xl font-light md:text-6xl">Una interfaz. Contexto conectado.</h1><p className="mt-4 max-w-2xl text-[var(--muted)]">Pregunta, registra una señal o convierte una fricción en trabajo observable. Ningún resultado de IA se activa sin revisión humana.</p></div>
        <UserButton />
      </header>

      <nav aria-label="Acciones de inteligencia" className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        {[['#ask','Ask KYRUMA'],['#radar','Review RADAR'],['#opportunities','See opportunities'],['#friction','Record friction']].map(([href, label]) => <a key={href} href={href} className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5 text-sm transition hover:border-[var(--primary)]">{label}<span className="float-right">→</span></a>)}
      </nav>

      <section id="ask" className={`${panel} mt-8 scroll-mt-24`}>
        <div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs uppercase tracking-[.22em] text-[var(--primary)]">Ask KYRUMA</p><h2 className="mt-3 text-3xl font-light">¿Qué necesitas hacer?</h2><p className="mt-4 text-sm leading-relaxed text-[var(--muted)]">La solicitud captura el contexto Brain y RADAR disponible, selecciona un workflow cuando corresponde y queda preparada para ejecución y revisión humana.</p></div>
          <form action={askKyrumaAction} className="space-y-4"><label className="text-sm">Solicitud<textarea className={`${field} mt-2 min-h-32`} maxLength={8000} name="request" placeholder="Ejemplo: crea cinco ideas de contenido para esta semana" required /></label><label className="text-sm">Intención<select className={`${field} mt-2`} name="intent" defaultValue="general"><option value="general">Resolver automáticamente</option>{dashboard.workflows.map((workflow) => <option key={workflow.key} value={workflow.key}>{workflow.name}</option>)}</select></label><ScopeFields workspaces={dashboard.workspaces} /><button className="rounded-full bg-[var(--primary)] px-6 py-3 text-sm font-medium text-black" type="submit">Preparar con KYRUMA AI</button></form>
        </div>
        <div className="mt-8 border-t border-[var(--border)] pt-6"><p className="text-xs uppercase tracking-[.18em] text-[var(--muted)]">Solicitudes recientes</p><div className="mt-4 grid gap-3 md:grid-cols-2">{dashboard.aiRequests.length ? dashboard.aiRequests.slice(0, 6).map((request) => <article key={request.id} className="rounded-2xl bg-[var(--surface-soft)] p-4"><div className="flex justify-between gap-4"><span className="text-xs uppercase tracking-[.14em] text-[var(--primary)]">{request.status}</span><span className="text-xs text-[var(--muted)]">{readableDate(request.createdAt)}</span></div><p className="mt-3 text-sm">{request.request}</p><p className="mt-3 text-xs text-[var(--muted)]">{request.selectedWorkflowKey ?? "Context routing"} · revisión humana obligatoria</p></article>) : <p className="text-sm text-[var(--muted)]">Todavía no hay solicitudes.</p>}</div></div>
      </section>

      <section id="radar" className={`${panel} mt-8 scroll-mt-24`}>
        <div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs uppercase tracking-[.22em] text-[var(--primary)]">KYRUMA RADAR</p><h2 className="mt-3 text-3xl font-light">Registro de decisiones</h2></div><span className="text-sm text-[var(--muted)]">{dashboard.radar.length} señales visibles</span></div>
        <div className="mt-6 grid gap-4 lg:grid-cols-2">{dashboard.radar.map((entry) => <article key={entry.id} className="rounded-2xl bg-[var(--surface-soft)] p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs text-[var(--primary)]">RADAR {entry.radarId}</p><h3 className="mt-2 text-xl font-light">{entry.title}</h3></div><span className="rounded-full border border-[var(--border)] px-3 py-1 text-xs">{entry.status}</span></div><p className="mt-4 text-sm text-[var(--muted)]">{entry.relatedModule} · impacto {entry.impactEstimate} · esfuerzo {entry.effortEstimate}</p>{entry.nextAction ? <p className="mt-4 text-sm">Siguiente: {entry.nextAction}</p> : null}{nextRadarStatuses(parseRadarStatus(entry.status)).length ? <form action={updateRadarStatusAction} className="mt-5 flex flex-wrap gap-2"><input name="id" type="hidden" value={entry.id} /><select className="rounded-full border border-[var(--border)] bg-transparent px-4 py-2 text-xs" name="status">{nextRadarStatuses(parseRadarStatus(entry.status)).map((status) => <option key={status} value={status}>{status}</option>)}</select><button className="rounded-full border border-[var(--primary)] px-4 py-2 text-xs" type="submit">Actualizar estado</button></form> : null}</article>)} </div>
        <details className="mt-6 rounded-2xl border border-[var(--border)] p-5"><summary className="cursor-pointer text-sm">Registrar nueva observación</summary><form action={addRadarEntryAction} className="mt-5 grid gap-4 md:grid-cols-2"><input className={field} name="radarId" placeholder="ID, por ejemplo 022" required /><input className={field} name="title" placeholder="Título" required /><input className={field} name="category" placeholder="Categoría" required /><input className={field} name="relatedModule" placeholder="Módulo relacionado" required /><textarea className={`${field} md:col-span-2`} name="problemOpportunity" placeholder="Problema u oportunidad detectada" /><textarea className={`${field} md:col-span-2`} name="potentialApplication" placeholder="Aplicación potencial" /><select className={field} name="impactEstimate" defaultValue="unknown"><option value="unknown">Impacto por estimar</option><option value="low">Impacto bajo</option><option value="medium">Impacto medio</option><option value="high">Impacto alto</option></select><select className={field} name="effortEstimate" defaultValue="unknown"><option value="unknown">Esfuerzo por estimar</option><option value="low">Esfuerzo bajo</option><option value="medium">Esfuerzo medio</option><option value="high">Esfuerzo alto</option></select><select className={field} name="priority" defaultValue="medium"><option value="low">Prioridad baja</option><option value="medium">Prioridad media</option><option value="high">Prioridad alta</option><option value="critical">Prioridad crítica</option></select><input className={field} name="sourceReference" placeholder="Fuente / referencia" /><textarea className={`${field} md:col-span-2`} name="nextAction" placeholder="Siguiente acción" /><button className="w-fit rounded-full bg-[var(--primary)] px-6 py-3 text-sm font-medium text-black" type="submit">Registrar en RADAR</button></form></details>
      </section>

      <section className={`${panel} mt-8`}>
        <div className="grid gap-10 lg:grid-cols-2"><div><p className="text-xs uppercase tracking-[.22em] text-[var(--primary)]">KYRUMA Brain</p><h2 className="mt-3 text-3xl font-light">Conocimiento con ámbito explícito</h2><div className="mt-6 space-y-3">{dashboard.brain.length ? dashboard.brain.slice(0, 8).map((record) => <article key={record.id} className="rounded-2xl bg-[var(--surface-soft)] p-4"><div className="flex justify-between gap-4"><p className="text-sm font-medium">{record.title}</p><span className="text-xs text-[var(--muted)]">{record.scopeType} · {record.dnaType}</span></div><p className="mt-2 text-xs text-[var(--muted)]">{record.recordType} · actualizado {readableDate(record.updatedAt)}</p></article>) : <p className="text-sm text-[var(--muted)]">El Brain está preparado y todavía no contiene registros aprobados.</p>}</div></div>
          <details className="rounded-2xl border border-[var(--border)] p-5"><summary className="cursor-pointer text-sm">Añadir conocimiento</summary><form action={addBrainRecordAction} className="mt-5 space-y-4"><div className="grid gap-3 md:grid-cols-2"><select className={field} name="scopeType">{brainScopes.map((scope) => <option key={scope} value={scope}>{scope}</option>)}</select><select className={field} name="dnaType">{brainDnaTypes.map((dna) => <option key={dna} value={dna}>{dna} DNA</option>)}</select></div><ScopeFields workspaces={dashboard.workspaces} /><input className={field} name="recordType" placeholder="Tipo: decisión, objetivo, restricción…" required /><input className={field} name="title" placeholder="Título" required /><textarea className={`${field} min-h-28`} maxLength={10000} name="content" placeholder="Conocimiento verificable" required /><input className={field} name="sourceReference" placeholder="Fuente opcional" /><p className="text-xs text-[var(--muted)]">GLOBAL no admite cliente; CLIENT requiere Workspace; PROJECT requiere Workspace y proyecto. El servidor valida estos límites.</p><button className="rounded-full bg-[var(--primary)] px-6 py-3 text-sm font-medium text-black" type="submit">Guardar en Brain</button></form></details></div>
      </section>

      <section id="opportunities" className={`${panel} mt-8 scroll-mt-24`}>
        <div className="grid gap-10 lg:grid-cols-[1fr_.85fr]"><div><p className="text-xs uppercase tracking-[.22em] text-[var(--primary)]">Opportunity Calendar</p><h2 className="mt-3 text-3xl font-light">Oportunidades, no un calendario vacío</h2><div className="mt-6 space-y-3">{dashboard.opportunities.length ? dashboard.opportunities.map((item) => <article key={item.id} className="flex items-start justify-between gap-5 rounded-2xl bg-[var(--surface-soft)] p-4"><div><p className="text-sm font-medium">{item.title}</p><p className="mt-2 text-xs text-[var(--muted)]">{item.opportunityType} · {item.status}</p></div><time className="text-xs text-[var(--primary)]">{readableDate(item.startsAt)}</time></article>) : <p className="text-sm text-[var(--muted)]">No hay oportunidades registradas. No se simulan tendencias sin una fuente conectada.</p>}</div></div>
          <form action={addOpportunityAction} className="space-y-4"><input className={field} name="title" placeholder="Oportunidad" required /><select className={field} name="opportunityType"><option value="important_date">Fecha importante</option><option value="commercial">Comercial</option><option value="cultural">Cultural</option><option value="sector">Sector</option><option value="campaign">Campaña</option><option value="content">Contenido previsto</option><option value="observed">Oportunidad observada</option><option value="trend">Tendencia con fuente</option></select><input className={field} defaultValue={defaultDate} name="startsAt" type="date" required /><textarea className={field} name="description" placeholder="Por qué importa" /><input className={field} name="sourceReference" placeholder="Fuente, si existe" /><ScopeFields workspaces={dashboard.workspaces} /><button className="rounded-full bg-[var(--primary)] px-6 py-3 text-sm font-medium text-black" type="submit">Añadir oportunidad</button></form></div>
      </section>

      <section className={`${panel} mt-8`}><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.22em] text-[var(--primary)]">Content Intelligence</p><h2 className="mt-3 text-3xl font-light">Hooks y workflows compartidos</h2></div><span className="text-sm text-[var(--muted)]">{dashboard.hooks.total}/{dashboard.hooks.target} hooks incorporados</span></div><div className="mt-6 grid gap-3 md:grid-cols-3">{hookBlocks.map((block, index) => <article key={block} className="rounded-2xl bg-[var(--surface-soft)] p-4"><p className="text-xs text-[var(--primary)]">0{index + 1}</p><p className="mt-2 text-sm">{block}</p><p className="mt-3 text-xs text-[var(--muted)]">{dashboard.hooks.byBlock[block]} hooks</p></article>)}</div><p className="mt-5 text-sm text-[var(--muted)]">La estructura de 44 hooks está preparada. Sus textos no estaban disponibles en el contexto recibido y no se han inventado.</p>
        <div className="mt-8 grid gap-4 md:grid-cols-2">{dashboard.workflows.map((workflow) => <article key={workflow.id} className="rounded-2xl border border-[var(--border)] p-5"><h3 className="font-medium">{workflow.name}</h3><p className="mt-2 text-sm text-[var(--muted)]">{workflow.description}</p><p className="mt-4 text-xs text-[var(--primary)]">v{workflow.version} · revisión humana</p></article>)}</div>
        <details className="mt-6 rounded-2xl border border-[var(--border)] p-5"><summary className="cursor-pointer text-sm">Incorporar un hook aprobado</summary><form action={addContentHookAction} className="mt-5 grid gap-4 md:grid-cols-2"><input className={field} name="hookId" placeholder="ID del hook" required /><input className={field} name="name" placeholder="Nombre" required /><select className={`${field} md:col-span-2`} name="block">{hookBlocks.map((block) => <option key={block} value={block}>{block}</option>)}</select><textarea className={field} name="explanation" placeholder="Explicación" /><textarea className={field} name="structure" placeholder="Estructura" /><textarea className={field} name="example" placeholder="Ejemplo" /><input className={field} name="recommendedObjective" placeholder="Objetivo recomendado" /><input className={field} name="applications" placeholder="Aplicaciones, separadas por comas" /><button className="w-fit rounded-full bg-[var(--primary)] px-6 py-3 text-sm font-medium text-black" type="submit">Guardar hook</button></form></details>
      </section>

      <section className={`${panel} mt-8`}><p className="text-xs uppercase tracking-[.22em] text-[var(--primary)]">KYRUMA Visual Recipes</p><h2 className="mt-3 text-3xl font-light">Recipes registradas, prompts protegidos</h2><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{dashboard.recipes.map((recipe) => <article key={recipe.id} className="rounded-2xl bg-[var(--surface-soft)] p-5"><div className="flex justify-between gap-4"><h3 className="text-xl font-light">{recipe.name}</h3><span className="text-xs text-[var(--muted)]">v{recipe.version}</span></div><p className="mt-4 text-xs uppercase tracking-[.14em] text-[var(--primary)]">{recipe.promptReady ? "Ready for test" : "Prompt pendiente"}</p><p className="mt-3 text-sm text-[var(--muted)]">El prompt maestro nunca se muestra en la interfaz.</p></article>)}</div></section>

      <section id="friction" className={`${panel} mt-8 scroll-mt-24`}><div className="grid gap-10 lg:grid-cols-[1fr_.9fr]"><div><p className="text-xs uppercase tracking-[.22em] text-[var(--primary)]">Operational Friction Audit</p><h2 className="mt-3 text-3xl font-light">Construir desde problemas observados</h2><div className="mt-6 space-y-3">{dashboard.frictions.length ? dashboard.frictions.map((item) => <article key={item.id} className="rounded-2xl bg-[var(--surface-soft)] p-4"><div className="flex justify-between gap-4"><p className="text-sm font-medium">{item.problem}</p><span className="text-xs text-[var(--primary)]">{item.priority}</span></div><p className="mt-3 text-xs text-[var(--muted)]">{item.area} · {item.frequency}{item.minutesLost !== null ? ` · ${item.minutesLost} min perdidos` : ""}</p></article>) : <p className="text-sm text-[var(--muted)]">Todavía no hay fricciones registradas.</p>}</div></div>
        <form action={addFrictionAction} className="space-y-4"><textarea className={field} name="problem" placeholder="Problema observado" required /><div className="grid gap-3 md:grid-cols-2"><input className={field} name="area" placeholder="Área" required /><input className={field} name="affectedPersona" placeholder="Persona afectada" required /></div><input className={field} name="frequency" placeholder="Frecuencia" required /><input className={field} min="0" name="minutesLost" placeholder="Minutos perdidos" type="number" /><textarea className={field} name="impact" placeholder="Impacto" required /><textarea className={field} name="currentWorkaround" placeholder="Solución actual" /><textarea className={field} name="potentialOsSolution" placeholder="Posible solución KYRUMA OS" /><textarea className={field} name="potentialAiSolution" placeholder="Posible solución KYRUMA AI" /><div className="grid gap-3 md:grid-cols-2"><select className={field} name="effortEstimate"><option value="unknown">Esfuerzo por estimar</option><option value="low">Bajo</option><option value="medium">Medio</option><option value="high">Alto</option></select><select className={field} name="priority"><option value="low">Prioridad baja</option><option value="medium">Prioridad media</option><option value="high">Prioridad alta</option><option value="critical">Prioridad crítica</option></select></div><input className={field} min="0" name="estimatedMinutesSaved" placeholder="Ahorro estimado en minutos" type="number" /><ScopeFields workspaces={dashboard.workspaces} /><button className="rounded-full bg-[var(--primary)] px-6 py-3 text-sm font-medium text-black" type="submit">Registrar fricción</button></form></div></section>

      <section className="mt-8 rounded-3xl border border-[var(--border)] p-6 text-sm text-[var(--muted)]"><p><strong className="text-[var(--foreground)]">Integraciones reales:</strong> Google Drive, Clerk, Resend y Event Bus. Gmail, Google Calendar, Metricool, WhatsApp y n8n no se muestran como conectados porque no existe una conexión verificada.</p></section>
    </div>
  </main>;
}
